kind: pipeline
name: build-deploy

environment:
  BACKEND_NAME: dentist-backend
  FRONT_NAME: dentist-front
  MYSQL_NAME: dentist-mysql
  REPO: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: shenjies88

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2
        - front-practice/node_modules

  - name: build-backend
    image: maven:3-alpine
    commands:
      - mvn -DskipTests clean package -Dmaven.repo.local=./.m2/repository
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - restore-cache

  #  - name: build-front
  #    image: node:latest
  #    commands:
  #      - cd front-practice
  #      - yarn
  #      - yarn build
  #    when:
  #      branch:
  #        - master
  #      event:
  #        - push
  #    depends_on:
  #      - build-backend
  #
  #  - name: rebuild-cache
  #    image: drillster/drone-volume-cache
  #    volumes:
  #      - name: cache
  #        path: /cache
  #    settings:
  #      rebuild: true
  #      mount:
  #        - ./.m2
  #        - front-practice/node_modules
  #    depends_on:
  #      - build-front

  - name: docker-buid-push
    image: plugins/docker
    settings:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
    commands:
      - sh docker_build.sh $${DRONE_BUILD_NUMBER} $${BACKEND_NAME} $${FRONT_NAME} $${MYSQL_NAME} $${REPO} $${NAMESPACE}
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend

  - name: deploy-rancher
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://192.168.56.20/v3
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1vSHZJSFh1VzBvWjYxcXNIUVUwQjFIb1ZON2tZaXJkNEM0UFQxRVNLOGsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tNXc3ZnIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRmN2YwYjJhLTVkOTUtNDdlNy1iMjhkLWRkNTI2ZDY2ZDVmMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.O6zEN6YPFB46R3lgpYAjtOZn9fGEbjvGhwLt1FNuAQR9UTXple4TvAwD1AMckgVTwTLkOFO3OJImupZNePECMo8JCVuQkCeAHtQ4tGwn6eeUhYzF_KKWQ8WRyNOO6yjA66io0zzkeKb9-a1Se839ce9h4P1Ld75eGuQarCrJ3s-YwH_6qc5CXRv8_3a8J3_4DoiD-gD7MDMRQaLBTJOiWC9zY65hGYnvRJ9EoGNPTF-A0VosUgPjqaYqetRcR3gzpi-LkwRXPEbH6vY55QSiawefyw9w4jSAjMTWMLoKU9_VxieCuxoEw9kwJd3Rft9aqJKRUFNlr_mZxgmCrvtEmw
      namespace: default
      deployment: $${MYSQL_NAME}
      repo: $${REPO}/$${NAMESPACE}
      container: $${MYSQL_NAME}
      tag: $${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - docker-buid-push

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock


      