kind: pipeline
name: build-deploy

environment:
  BACKEND_NAME: dentist-backend
  FRONT_NAME: dentist-front
  MYSQL_NAME: dentist-mysql
  REPO: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: shenjies88

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2
        - front-practice/node_modules

  - name: build-backend
    image: maven:3-alpine
    commands:
      - mvn -DskipTests clean package -Dmaven.repo.local=./.m2/repository
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - restore-cache

  #  - name: build-front
  #    image: node:latest
  #    commands:
  #      - cd front-practice
  #      - yarn
  #      - yarn build
  #    when:
  #      branch:
  #        - master
  #      event:
  #        - push
  #    depends_on:
  #      - build-backend
  #
  #  - name: rebuild-cache
  #    image: drillster/drone-volume-cache
  #    volumes:
  #      - name: cache
  #        path: /cache
  #    settings:
  #      rebuild: true
  #      mount:
  #        - ./.m2
  #        - front-practice/node_modules
  #    depends_on:
  #      - build-front

  - name: docker-buid-push
    image: plugins/docker
    settings:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
    commands:
      - sh docker_build.sh $${DRONE_BUILD_NUMBER} $${BACKEND_NAME} $${FRONT_NAME} $${MYSQL_NAME} $${REPO} $${NAMESPACE}
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend

  - name: deploy-rancher
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://192.168.56.20
      kubernetes_token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltMXZTSFpKU0ZoMVZ6QnZXall4Y1hOSVVWVXdRakZJYjFaT04ydFphWEprTkVNMFVGUXhSVk5MT0dzaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dE5YYzNabklpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbVJtTjJZd1lqSmhMVFZrT1RVdE5EZGxOeTFpTWpoa0xXUmtOVEkyWkRZMlpEVm1NaUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEuTzZ6RU42WVBGQjQ2UjNsZ3BZQWp0T1puOWZHRWJqdkdod0x0MUZOdUFRUjlVVFhwbGU0VHZBd0QxQU1ja2dWVHdUTGtPRk8zT0pJbXVwWk5lUEVDTW84SkNWdVFrQ2VBSHRRNHRHd242ZWVVaFl6Rl9LS1dROFdSeU5PTzZ5akE2NmlvMHp6a2VLYjktYTFTZTgzOWNlOWg0UDFMZDc1ZUd1UWFyQ3JKM3MtWXdIXzZxYzVDWFJ2OF8zYThKM180RG9pRC1nRDdNRE1SUWFMQlRKT2lXQzl6WTY1aEdZbnZSSjlFb0dOUFRGLUEwVm9zVWdQanFhWXFldFJjUjNnenBpLUxrd1JYUEViSDZ2WTU1UVNpYXdlZnl3OXc0alNBak1UV01Mb0tVOV9WeGllQ3V4b0V3OWt3SmQzUmZ0OWFxSktSVUZObHJfbVp4Z21DcnZ0RW13
      namespace: default
      deployment: $${MYSQL_NAME}
      repo: $${REPO}/$${NAMESPACE}
      container: $${MYSQL_NAME}
      tag: $${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - docker-buid-push

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock


      