kind: pipeline
type: docker
name: build-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: build-backend
    image: maven:3.3-jdk-8
    commands:
      - mvn clean package -DskipTest
    when:
      branch:
        - master
      event:
        - push

  - name: build-front
    image: node:10
    commands:
      - cd dentist-front
      - yarn
      - yarn build
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend
#
#  - name: deploy

#    commands:
#      - docker-compose build
#      - docker image prune -f
#      - docker-compose up -d
#    when:
#      branch:
#        - master
#      event:
#        - push
#    depends_on:
#      - build-backend
#      - build-front