kind: pipeline
type: docker
name: build-deploy

steps:

  - name: build
    image: maven:3-alpine
    commands:
      - mvn -DskipTests clean package -Dmaven.repo.local=./.m2/repository
    when:
      branch:
        - master
      event:
        - push

  - name: build-front
  	image: node:latest
    commands:
      - cd front-practice
      - yarn
      - yarn build
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend

  - name: deploy
  	image: docker/compose
    commands:
      - docker-compose down
      - docker-compose build
      - docker image prune -f
      - docker-compose up -d
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend
      - build-front