kind: pipeline
name: build-deploy

environment:
  BACKEND_NAME: dentist-backend
  FRONT_NAME: dentist-front
  MYSQL_NAME: dentist-mysql
  REPO: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: shenjies88
  TAG: $${DRONE_BUILD_NUMBER}

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2
        - front-practice/node_modules

  - name: build-backend
    image: maven:3-alpine
    commands:
      - mvn -DskipTests clean package -Dmaven.repo.local=./.m2/repository
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - restore-cache

  #  - name: build-front
  #    image: node:latest
  #    commands:
  #      - cd front-practice
  #      - yarn
  #      - yarn build
  #    when:
  #      branch:
  #        - master
  #      event:
  #        - push
  #    depends_on:
  #      - build-backend
  #
  #  - name: rebuild-cache
  #    image: drillster/drone-volume-cache
  #    volumes:
  #      - name: cache
  #        path: /cache
  #    settings:
  #      rebuild: true
  #      mount:
  #        - ./.m2
  #        - front-practice/node_modules
  #    depends_on:
  #      - build-front

  - name: docker-buid-push-mysql
    image: plugins/docker
    settings:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
    commands:
      - docker -v
      - nohup dockerd &
      - docker login -u $${PLUGIN_DOCKER_USERNAME} -p $${PLUGIN_DOCKER_PASSWORD} $${REPO}
      - docker build --rm=true -f dockerfile-mysql -t $${REPO}/$${NAMESPACE}/$${MYSQL_NAME}:$${TAG} .
      - docker tag $${MYSQL_NAME} $${REPO}/$${NAMESPACE}/$${MYSQL_NAME}:$${TAG}
      - docker push $${REPO}/$${NAMESPACE}/$${MYSQL_NAME}:$${TAG}
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - master
      event:
        - push

#  rancher:
#    image: peloton/drone-rancher
#    url: http://https://192.168.56.20/p/c-257p4:p-9nj7t/
#    access_key: ${RANCHER_ACCESS_KEY}
#    secret_key: ${RANCHER_SECRET_KEY}
#    service: rancher_stack/rancher_service
#    docker_image: $${REPO}/$${NAMESPACE}/$${BACKEND_NAME}:$${DRONE_BUILD_NUMBER}
#    batch_size: 1
#    timeout: 600
#    confirm: true
#    when:
#      branch:
#        - master
#      event:
#        - push
#    depends_on:
#      - docker-build-push


volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock


      