kind: pipeline
name: build-deploy

environment:
  DOCKER_TAG: $${DRONE_BUILD_NUMBER}
  BACKEND_NAME: dentist-backend
  FRONT_NAME: dentist-front
  MYSQL_NAME: dentist-mysql
  REPO: registry.cn-hangzhou.aliyuncs.com

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2
        - front-practice/node_modules

  - name: build-backend
    image: maven:3-alpine
    commands:
      - mvn -DskipTests clean package -Dmaven.repo.local=./.m2/repository
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - restore-cache

  - name: build-front
    image: node:latest
    commands:
      - cd front-practice
      - yarn
      - yarn build
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - build-backend

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.m2
        - front-practice/node_modules
    depends_on:
      - build-front

  - name: docker-build
    image: docker/compose
    commands:
      - docker-compose build
      - docker image prune -y
    volumes:
      - name: docker
        path: /var/run/docker.sock
    depends_on:
      - build-front

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock


      