stages:
  - build
  - push

cache:
  paths:
    - front-practice/node_modules/
    - front-practice/dist/
    - ./.m2/repository
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  image: maven:3.6.3-jdk-8
  script:
    - mvn clean package -DskipTests -Dmaven.repo.local=./.m2/repository
  only:
    - master
    - pushes
  tags:
    - vue-springboot

push:
  stage: push
  image: docker:latest
  environment:
    - REPO: registry.cn-hangzhou.aliyuncs.com
    - NAME_SPACE: shenjies88
    - APP_NAME: dentist-backend
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $REPO
    - docker build --rm=true -f dockerfile-backend -t $REPO/$NAME_SPACE/$APP_NAME:$CI_COMMIT_SHA .
    - docker push $REPO/$NAME_SPACE/$APP_NAME:$CI_COMMIT_SHA
    - docker rmi $REPO/$NAME_SPACE/$APP_NAME:$CI_COMMIT_SHA
  only:
    - master
    - pushes
  tags:
    - vue-springboot


