stages:
  - build
  - push-image
  - deploy

cache:
  paths:
    - front-practice/dist/
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  script:
    - mvn clean package -DskipTests
  only:
    - master
    - pushes
  tags:
    - vue-springboot

build-front:
  stage: build
  script:
    - cd front-practice
    - yarn
    - yarn build
  only:
    - master
    - pushes
  tags:
    - vue-springboot

push-backend:
  stage: push-image
  script:
    - bash docker_build_push.sh $CI_COMMIT_SHA dentist-backend dentist-front registry.cn-hangzhou.aliyuncs.com shenjies88 $DOCKER_USERNAME $DOCKER_PASSWORD
  only:
    - master
    - pushes
  tags:
    - vue-springboot

deploy-backend:
  stage: deploy
  script:
    - kubectl set image deployment/dentist-backend -n app dentist-backend=dentist-backend:$CI_COMMIT_SHA
  only:
    - master
    - pushes
  tags:
    - vue-springboot


