stages:
  - build

cache:
  paths:
    - front-practice/node_modules/
    - front-practice/dist/
    - ./.m2/repository
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  image: maven:3.6.3-jdk-8
  script:
    - mvn clean package -DskipTests -Dmaven.repo.local=./.m2/repository
  only:
    - master
    - pushes
  tags:
    - vue-springboot

#build-front:
#  stage: build
#  image: node:latest
#  script:
#    - yarn
#    - yarn biuld
#  only:
#    - master
#    - pushes
#  tags:
#    - vue-springboot