stages:
  - build
  - push-image
  - deploy

variables:
  BACKEND_NAME: dentist-backend
  FRONT_NAME: dentist-front
  REPO: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: shenjies88

cache:
  paths:
    - front-practice/dist/
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  script:
    - mvn clean package -DskipTests
  only:
    - master
    - pushes
  tags:
    - vue-springboot

build-front:
  stage: build
  script:
    - cd front-practice
    - yarn
    - yarn build
  only:
    - master
    - pushes
  tags:
    - vue-springboot

push-backend:
  stage: push-image
  script:
    - bash docker_build_push.sh ${CI_COMMIT_SHA} ${BACKEND_NAME} ${FRONT_NAME} ${REPO} ${NAMESPACE} ${DOCKER_USERNAME} ${DOCKER_PASSWORD}
  only:
    - master
    - pushes
  tags:
    - vue-springboot

deploy-backend:
  stage: deploy
  script:
    - kubectl set image deployment/${BACKEND_NAME} -n app ${BACKEND_NAME}=${REPO}/${NAMESPACE}/${BACKEND_NAME}:${CI_COMMIT_SHA}
    - kubectl set image deployment/${FRONT_NAME} -n app ${FRONT_NAME}=${REPO}/${NAMESPACE}/${FRONT_NAME}:${CI_COMMIT_SHA}
  only:
    - master
    - pushes
  tags:
    - vue-springboot


