stages:
  - build
  - push-image

cache:
  paths:
    - front-practice/dist/
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  script:
    - mvn clean package -DskipTests
  only:
    - master
    - pushes
  tags:
    - vue-springboot

push-backend:
  stage: push-image
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
    - docker build --rm=true -f dockerfile-backend -t registry.cn-hangzhou.aliyuncs.com/shenjies88/dentist-backend:$CI_COMMIT_SHA .
    - docker push registry.cn-hangzhou.aliyuncs.com/shenjies88/dentist-backend:$CI_COMMIT_SHA
    - docker rmi registry.cn-hangzhou.aliyuncs.com/shenjies88/dentist-backend:$CI_COMMIT_SHA
  only:
    - master
    - pushes
  tags:
    - vue-springboot

