stages:
  - build

cache:
  paths:
    - front-practice/node_modules/
    - front-practice/dist/
    - target/practice-backend-0.0.1-SNAPSHOT.jar

build-backend:
  stage: build
  image: maven:3.6.3-jdk-8
  script:
    - mvn clean package -DskipTests
  only:
    - master
  tags:
    - vue-springboot

build-front:
  stage: build
  image: node:latest
  script:
    - yarn
    - yarn biuld
  only:
    - master
  tags:
    - vue-springboot