version: '3'
services:

  dentist-mysql:
    image: ${MYSQL_NAME}:${DOCKER_TAG}
    container_name: ${MYSQL_NAME}
    build:
      context: .
      dockerfile: dockerfile-mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: [
      --log-bin=mysql-bin,
      --server-id=1
    ]
    networks:
      - dentist-net

  dentist-backend:
    image: ${BACKEND_NAME}:${DOCKER_TAG}
    container_name: ${BACKEND_NAME}
    build:
      context: .
      dockerfile: dockerfile-backend
    ports:
      - 8080:8080
    depends_on:
      - dentist-mysql
    networks:
      - dentist-net

  dentist-front:
    image: ${FRONT_NAME}:${DOCKER_TAG}
    container_name: ${FRONT_NAME}
    build:
      context: .
      dockerfile: dockerfile-front
    ports:
      - 8000:80
    depends_on:
      - dentist-mysql
      - dentist-backend
    networks:
      - dentist-net

networks:
  dentist-net: